ollama:
  base_url: "http://localhost:11434"
  model: "qwen2.5-coder:1.5b-base"
  temperature: 0.7
  max_tokens: 100

terminal:
  prompt: "> "
  history_file: "~/.nova_history"
  max_history: 1000
  completion_threshold: 0.5

style:
  prompt: "bold #00ff00"
  suggestion: "italic #0000ff"
  error: "bold #ff0000"
  info: "#00ffff"
  nova: "bold #0000ff"
  path: "#00ff00" 