ollama:
  base_url: "http://localhost:11434"
  model: "qwen2.5-coder:1.5b-base"
  temperature: 0.7

terminal:
  prompt: "> "
  history_file: "~/.nova_history"
  max_history: 1000

style:
  prompt: "bold #00ff00"    # Bold green for prompt
  suggestion: "italic #0000ff"  # Italic blue for suggestions
  error: "bold #ff0000"     # Bold red for errors
  info: "#00ffff"           # Cyan for info
  nova: "bold #67038f"      # Bold purple for NOVA
  path: "#00ab0e"           # Green for path 